[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''

[[redirects]]
  from = "/evenementen/"
  to = "/jams"
  status = 301

[[redirects]]
  from = "/kennisbank/wat-zijn-goede-schoenen-voor-freerunning/"
  to = "/kleding"
  status = 301

[[redirects]]
  from = "/kennisbank/"
  to = "/"
  status = 301

[[redirects]]
  from = "/images/gyms/*/:file"
  to = "/.netlify/images/?url=/images/:file&w=800&h=400"
  status = 200